'use client'

import { useState, useCallback } from 'react'
import type { GeneratedProject, BuilderState } from '@/lib/builder-types'
import JSZip from 'jszip'

function generateMockProject(prompt: string): GeneratedProject {
  const ts = `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My AI Landing Page',
  description: 'Generated by Vybex AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`

  const pageTsx = `'use client'

import { motion } from 'framer-motion'
import { ArrowRight, Zap, Shield, BarChart3 } from 'lucide-react'

export default function Home() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white">
      {/* Hero Section */}
      <section className="relative flex flex-col items-center justify-center min-h-screen px-4 text-center">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-green-500/10 rounded-full blur-3xl" />
          <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-green-500/5 rounded-full blur-3xl" />
        </div>
        <motion.div
          initial={{ opacity: 0, y: 32 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="relative z-10 max-w-4xl mx-auto"
        >
          <span className="inline-block px-4 py-1.5 mb-6 text-xs font-semibold tracking-widest text-green-400 border border-green-400/30 rounded-full bg-green-400/5">
            POWERED BY AI
          </span>
          <h1 className="text-5xl md:text-7xl font-bold leading-tight mb-6">
            ${prompt.slice(0, 30) || 'Your Amazing'}{' '}
            <span className="text-green-400">Product</span>
          </h1>
          <p className="text-lg md:text-xl text-gray-400 max-w-2xl mx-auto mb-10">
            ${prompt.slice(0, 100) || 'The next generation platform that transforms how you work, built with cutting-edge AI technology.'}
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="flex items-center gap-2 px-8 py-4 rounded-xl bg-green-400 text-black font-semibold text-base hover:bg-green-300 transition-all duration-200">
              Get Started <ArrowRight className="w-5 h-5" />
            </button>
            <button className="flex items-center gap-2 px-8 py-4 rounded-xl border border-white/10 text-white font-semibold text-base hover:border-white/30 transition-all duration-200">
              View Demo
            </button>
          </div>
        </motion.div>
      </section>

      {/* Features Section */}
      <section className="py-24 px-4">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-16">
            Why <span className="text-green-400">Choose Us</span>
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { icon: Zap, title: 'Lightning Fast', desc: 'Blazing performance powered by the latest tech stack.' },
              { icon: Shield, title: 'Secure by Default', desc: 'Enterprise-grade security baked in from day one.' },
              { icon: BarChart3, title: 'Data Driven', desc: 'Real-time analytics and insights at your fingertips.' },
            ].map(({ icon: Icon, title, desc }) => (
              <div key={title} className="p-6 rounded-2xl border border-white/10 bg-white/5 hover:border-green-400/30 transition-all duration-300">
                <Icon className="w-8 h-8 text-green-400 mb-4" />
                <h3 className="text-xl font-semibold mb-2">{title}</h3>
                <p className="text-gray-400 text-sm">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  )
}`

  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #0a0a0a;
  --foreground: #ffffff;
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: 'Inter', sans-serif;
}`

  const tailwindConfig = `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        accent: '#00ff41',
      },
    },
  },
  plugins: [],
}
export default config`

  const packageJson = `{
  "name": "vybex-generated-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "framer-motion": "^11.0.0",
    "lucide-react": "^0.400.0",
    "next": "14.2.0",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}`
  const fileMap: Record<string, { content: string; language: string }> = {
    'app/page.tsx': { content: pageTsx, language: 'typescript' },
    'app/layout.tsx': { content: ts, language: 'typescript' },
    'app/globals.css': { content: globalsCss, language: 'css' },
    'tailwind.config.ts': { content: tailwindConfig, language: 'typescript' },
    'package.json': { content: packageJson, language: 'json' },
  }

  const files = [
    {
      name: 'app',
      path: 'app',
      type: 'folder' as const,
      children: [
        { name: 'page.tsx', path: 'app/page.tsx', type: 'file' as const, language: 'typescript' },
        { name: 'layout.tsx', path: 'app/layout.tsx', type: 'file' as const, language: 'typescript' },
        { name: 'globals.css', path: 'app/globals.css', type: 'file' as const, language: 'css' },
      ],
    },
    { name: 'tailwind.config.ts', path: 'tailwind.config.ts', type: 'file' as const, language: 'typescript' },
    { name: 'package.json', path: 'package.json', type: 'file' as const, language: 'json' },
  ]

  return { files, fileMap }
}

export function useBuilder() {
  const [state, setState] = useState<BuilderState>({
    project: null,
    activeFilePath: null,
    openTabs: [],
    isLoading: false,
    status: null,
    error: null,
  })
  const [prompt, setPromptState] = useState('')

  const generate = useCallback(async (p: string) => {
    setState(s => ({ ...s, isLoading: true, status: 'Generating folder structure...', error: null }))
    setPromptState(p)

    try {
      const steps = [
        'Generating folder structure...',
        'Writing page.tsx...',
        'Adding components...',
        'Styling with Tailwind...',
        'Finalizing UI elements...'
      ]

      // Start the actual generation
      const apiPromise = fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: p }),
      })

      // Show some initial steps
      for (let i = 0; i < 3; i++) {
        await new Promise(r => setTimeout(r, 600))
        setState(s => ({ ...s, status: steps[i] }))
      }

      const response = await apiPromise
      const data = await response.json()

      if (!response.ok) {
        setState(s => ({ ...s, isLoading: false, status: null, error: data.error || 'Failed to generate project' }))
        return
      }

      // Finish remaining steps
      for (let i = 3; i < steps.length; i++) {
        setState(s => ({ ...s, status: steps[i] }))
        await new Promise(r => setTimeout(r, 400))
      }

      setState({
        project: data,
        activeFilePath: 'app/page.tsx',
        openTabs: ['app/page.tsx'],
        isLoading: false,
        status: null,
        error: null,
      })
    } catch (err: any) {
      console.error('Generation failure:', err)
      setState(s => ({ ...s, isLoading: false, status: null, error: err.message || 'Service unavailable' }))
    }
  }, [])

  const setActiveFile = useCallback((path: string) => {
    setState(s => ({
      ...s,
      activeFilePath: path,
      openTabs: s.openTabs.includes(path) ? s.openTabs : [...s.openTabs, path],
    }))
  }, [])

  const closeTab = useCallback((path: string) => {
    setState(s => {
      const newTabs = s.openTabs.filter(t => t !== path)
      const newActive = path === s.activeFilePath ? (newTabs[newTabs.length - 1] ?? null) : s.activeFilePath
      return { ...s, openTabs: newTabs, activeFilePath: newActive }
    })
  }, [])

  const regenerate = useCallback(async () => {
    if (!prompt) return
    generate(prompt)
  }, [prompt, generate])

  const downloadZip = useCallback(async () => {
    if (!state.project) return
    const zip = new JSZip()
    Object.entries(state.project.fileMap).forEach(([path, { content }]) => {
      zip.file(path, content)
    })
    const blob = await zip.generateAsync({ type: 'blob' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'vybex-generated-app.zip'
    a.click()
    URL.revokeObjectURL(url)
  }, [state.project])

  const reset = useCallback(() => {
    setState({
      project: null,
      activeFilePath: null,
      openTabs: [],
      isLoading: false,
      status: null,
      error: null,
    })
    setPromptState('')
  }, [])

  return {
    ...state,
    prompt,
    generate,
    setActiveFile,
    closeTab,
    regenerate,
    downloadZip,
    reset,
  }
}
